<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Seed 25+ realistic hardware-store transactions that simulate
 * data arriving from HRMS, Supply Chain, E-Commerce, Fleet, and Facilities.
 * Each transaction is pre-evaluated by the AIService rules so the statuses,
 * confidence scores, and anomaly flags are consistent with our AI engine.
 */
class TransactionSeeder extends Seeder
{
    public function run(): void
    {
        // Grab subsystem IDs
        $subsystems = DB::table('subsystems')->pluck('id', 'slug')->toArray();
        $glId   = $subsystems['general-ledger'] ?? null;
        $apId   = $subsystems['accounts-payable'] ?? null;
        $arId   = $subsystems['accounts-receivable'] ?? null;
        $disbId = $subsystems['disbursement-management'] ?? null;

        $transactions = [
            // ───── SUPPLY CHAIN (Supplier Invoices → AP) ─────
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0041',
                'type' => 'EXPENSE',
                'amount' => 185000.00,
                'tax_amount' => 22200.00,
                'fee_amount' => 0.00,
                'description' => 'Bulk purchase of Portland Cement (500 bags) from National Hardware Supply',
                'status' => 'approved',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0042',
                'type' => 'EXPENSE',
                'amount' => 342500.00,
                'tax_amount' => 41100.00,
                'fee_amount' => 0.00,
                'description' => 'Deformed steel bars (10mm, 12mm, 16mm) — 200 pieces from MetalCraft Industries',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0043',
                'type' => 'EXPENSE',
                'amount' => 750000.00,
                'tax_amount' => 90000.00,
                'fee_amount' => 0.00,
                'description' => 'Heavy equipment rental — Backhoe Loader (30-day contract) from EquipMax Corp',
                'status' => 'ai_flagged',
                'ai_confidence_score' => 0.7450,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => true,
                'ai_anomaly_reason' => 'High-value transaction (PHP 750,000.00) exceeds threshold of PHP 500,000.00. Requires mandatory human review.',
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0044',
                'type' => 'EXPENSE',
                'amount' => 67800.00,
                'tax_amount' => 8136.00,
                'fee_amount' => 0.00,
                'description' => 'Assorted plywood sheets (4x8 marine, ordinary) — 150 pcs from WoodWorks PH',
                'status' => 'approved',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0045',
                'type' => 'EXPENSE',
                'amount' => 124500.00,
                'tax_amount' => 14940.00,
                'fee_amount' => 0.00,
                'description' => 'Boysen paint, primers, and coating supplies — quarterly restock from ColorWorld Dist.',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0046',
                'type' => 'EXPENSE',
                'amount' => 98200.00,
                'tax_amount' => 11784.00,
                'fee_amount' => 0.00,
                'description' => 'PVC pipes (various sizes), fittings, and valves from PipeLink Trading',
                'status' => 'approved',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],

            // ───── E-COMMERCE (Sales Revenue → AR) ─────
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10221',
                'type' => 'INCOME',
                'amount' => 45600.00,
                'tax_amount' => 5472.00,
                'fee_amount' => 912.00,
                'description' => 'Online order settlement — construction nails, screws, and bolts assortment (Batch #10221)',
                'status' => 'approved',
                'ai_confidence_score' => 0.9850,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SALES_REVENUE',
            ],
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10222',
                'type' => 'INCOME',
                'amount' => 128900.00,
                'tax_amount' => 15468.00,
                'fee_amount' => 2578.00,
                'description' => 'Walk-in customer bulk purchase — Roofing sheets and trusses for house construction',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.9850,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SALES_REVENUE',
            ],
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10223',
                'type' => 'INCOME',
                'amount' => 23400.00,
                'tax_amount' => 2808.00,
                'fee_amount' => 468.00,
                'description' => 'Online order — Electrical wiring supplies, circuit breakers, and junction boxes',
                'status' => 'approved',
                'ai_confidence_score' => 0.9850,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SALES_REVENUE',
            ],
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10224',
                'type' => 'INCOME',
                'amount' => 89700.00,
                'tax_amount' => 10764.00,
                'fee_amount' => 1794.00,
                'description' => 'Contractor account purchase — Tiles, grout, adhesive for commercial building project',
                'status' => 'approved',
                'ai_confidence_score' => 0.9850,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SALES_REVENUE',
            ],
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'REF-2026-0031',
                'type' => 'INCOME',
                'amount' => 12500.00,
                'tax_amount' => 1500.00,
                'fee_amount' => 250.00,
                'description' => 'Customer refund — Defective hollow blocks returned (Batch #REF-0031)',
                'status' => 'ai_flagged',
                'ai_confidence_score' => 0.9300,
                'ai_suggested_gl_code' => '4100-REF',
                'ai_suggested_gl_name' => 'Customer Refunds and Returns',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'CUSTOMER_REFUND',
            ],

            // ───── HRMS (Payroll & Claims → Disbursement) ─────
            [
                'subsystem_id' => $disbId,
                'source_module' => 'HRMS',
                'external_reference_id' => 'PAY-2026-M07-A',
                'type' => 'EXPENSE',
                'amount' => 285000.00,
                'tax_amount' => 34200.00,
                'fee_amount' => 0.00,
                'description' => 'July 2026 Payroll — Warehouse staff, delivery drivers, and cashiers (1st half)',
                'status' => 'approved',
                'ai_confidence_score' => 0.9620,
                'ai_suggested_gl_code' => '5100-EXP',
                'ai_suggested_gl_name' => 'Salaries and Compensation Expense',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'PAYROLL_SALARY',
            ],
            [
                'subsystem_id' => $disbId,
                'source_module' => 'HRMS',
                'external_reference_id' => 'PAY-2026-M07-B',
                'type' => 'EXPENSE',
                'amount' => 285000.00,
                'tax_amount' => 34200.00,
                'fee_amount' => 0.00,
                'description' => 'July 2026 Payroll — Warehouse staff, delivery drivers, and cashiers (2nd half)',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.9620,
                'ai_suggested_gl_code' => '5100-EXP',
                'ai_suggested_gl_name' => 'Salaries and Compensation Expense',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'PAYROLL_SALARY',
            ],
            [
                'subsystem_id' => $disbId,
                'source_module' => 'HRMS',
                'external_reference_id' => 'CLM-2026-0091',
                'type' => 'EXPENSE',
                'amount' => 18500.00,
                'tax_amount' => 0.00,
                'fee_amount' => 0.00,
                'description' => 'Employee reimbursement — Site supervisor transportation and meal allowance for June',
                'status' => 'approved',
                'ai_confidence_score' => 0.9100,
                'ai_suggested_gl_code' => '5120-EXP',
                'ai_suggested_gl_name' => 'Employee Reimbursement Claims',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'EMPLOYEE_CLAIM',
            ],
            [
                'subsystem_id' => $disbId,
                'source_module' => 'HRMS',
                'external_reference_id' => 'CLM-2026-0092',
                'type' => 'EXPENSE',
                'amount' => 520000.00,
                'tax_amount' => 0.00,
                'fee_amount' => 0.00,
                'description' => 'SUSPICIOUS — Unverified reimbursement claim from terminated employee account',
                'status' => 'ai_flagged',
                'ai_confidence_score' => 0.4200,
                'ai_suggested_gl_code' => '5120-EXP',
                'ai_suggested_gl_name' => 'Employee Reimbursement Claims',
                'ai_anomaly_flag' => true,
                'ai_anomaly_reason' => "Risk keyword detected in description: 'SUSPICIOUS'.",
                'category_type' => 'EMPLOYEE_CLAIM',
            ],

            // ───── FLEET (Fuel & Maintenance → Disbursement) ─────
            [
                'subsystem_id' => $disbId,
                'source_module' => 'FLEET',
                'external_reference_id' => 'FLT-FUEL-2026-07',
                'type' => 'EXPENSE',
                'amount' => 42000.00,
                'tax_amount' => 5040.00,
                'fee_amount' => 0.00,
                'description' => 'Monthly diesel fuel for 6 delivery trucks — Shell Fleet Card July 2026',
                'status' => 'approved',
                'ai_confidence_score' => 0.9100,
                'ai_suggested_gl_code' => '5300-EXP',
                'ai_suggested_gl_name' => 'Transportation and Logistics Expense',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'FLEET_FUEL',
            ],
            [
                'subsystem_id' => $disbId,
                'source_module' => 'FLEET',
                'external_reference_id' => 'FLT-MNT-2026-014',
                'type' => 'EXPENSE',
                'amount' => 65000.00,
                'tax_amount' => 7800.00,
                'fee_amount' => 0.00,
                'description' => 'Truck #3 engine overhaul and brake replacement — AutoPro Service Center',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.8950,
                'ai_suggested_gl_code' => '5310-EXP',
                'ai_suggested_gl_name' => 'Fleet Maintenance and Repairs',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'FLEET_MAINTENANCE',
            ],

            // ───── FACILITIES / LEGAL → Disbursement ─────
            [
                'subsystem_id' => $disbId,
                'source_module' => 'FACILITIES_LEGAL',
                'external_reference_id' => 'FAC-RENT-2026-07',
                'type' => 'EXPENSE',
                'amount' => 150000.00,
                'tax_amount' => 18000.00,
                'fee_amount' => 0.00,
                'description' => 'Monthly warehouse and showroom rental — July 2026 (Main Branch, Quezon City)',
                'status' => 'approved',
                'ai_confidence_score' => 0.9550,
                'ai_suggested_gl_code' => '5400-EXP',
                'ai_suggested_gl_name' => 'Occupancy and Facility Lease Expense',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'FACILITY_RENT',
            ],
            [
                'subsystem_id' => $disbId,
                'source_module' => 'FACILITIES_LEGAL',
                'external_reference_id' => 'LEG-2026-0008',
                'type' => 'EXPENSE',
                'amount' => 85000.00,
                'tax_amount' => 10200.00,
                'fee_amount' => 0.00,
                'description' => 'Legal retainer fee — Business permit renewal and SEC compliance advisory Q3 2026',
                'status' => 'pending_approval',
                'ai_confidence_score' => 0.9200,
                'ai_suggested_gl_code' => '5500-EXP',
                'ai_suggested_gl_name' => 'Legal and Professional Services',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'LEGAL_BILLING',
            ],

            // ───── MORE FLAGGED (for demo drama) ─────
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0099',
                'type' => 'EXPENSE',
                'amount' => 1200000.00,
                'tax_amount' => 144000.00,
                'fee_amount' => 0.00,
                'description' => 'OFFSHORE supplier — Imported Chinese steel rebar containers (20ft) via unknown vendor',
                'status' => 'ai_flagged',
                'ai_confidence_score' => 0.3100,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => true,
                'ai_anomaly_reason' => "Risk keyword detected in description: 'OFFSHORE'. High-value transaction (PHP 1,200,000.00) exceeds threshold.",
                'category_type' => 'SUPPLIER_INVOICE',
            ],
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10250',
                'type' => 'INCOME',
                'amount' => 890000.00,
                'tax_amount' => 106800.00,
                'fee_amount' => 17800.00,
                'description' => 'Government infrastructure project bid — Bulk cement, rebar, and aggregate supply',
                'status' => 'ai_flagged',
                'ai_confidence_score' => 0.7100,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => true,
                'ai_anomaly_reason' => 'High-value transaction (PHP 890,000.00) exceeds threshold of PHP 500,000.00. Requires mandatory human review.',
                'category_type' => 'SALES_REVENUE',
            ],

            // ───── EXTRA approved for volume ─────
            [
                'subsystem_id' => $arId,
                'source_module' => 'ECOMMERCE_CORE',
                'external_reference_id' => 'ORD-2026-10225',
                'type' => 'INCOME',
                'amount' => 15800.00,
                'tax_amount' => 1896.00,
                'fee_amount' => 316.00,
                'description' => 'Walk-in retail — Door hinges, padlocks, and cabinet handles',
                'status' => 'approved',
                'ai_confidence_score' => 0.9850,
                'ai_suggested_gl_code' => '4000-REV',
                'ai_suggested_gl_name' => 'E-Commerce Sales Revenue',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SALES_REVENUE',
            ],
            [
                'subsystem_id' => $apId,
                'source_module' => 'SUPPLY_CHAIN',
                'external_reference_id' => 'PO-2026-0047',
                'type' => 'EXPENSE',
                'amount' => 54000.00,
                'tax_amount' => 6480.00,
                'fee_amount' => 0.00,
                'description' => 'Electrical supplies restock — Panasonic switches, outlets, and wire rolls',
                'status' => 'approved',
                'ai_confidence_score' => 0.9410,
                'ai_suggested_gl_code' => '2100-AP',
                'ai_suggested_gl_name' => 'Accounts Payable — Trade Suppliers',
                'ai_anomaly_flag' => false,
                'ai_anomaly_reason' => null,
                'category_type' => 'SUPPLIER_INVOICE',
            ],
        ];

        $now = now();

        foreach ($transactions as $index => $tx) {
            $createdAt = $now->copy()->subDays(rand(0, 20))->subHours(rand(1, 23));
            $netAmount = $tx['amount'] - $tx['tax_amount'] - $tx['fee_amount'];
            $txId = (string) Str::uuid();

            DB::table('transactions')->insert([
                'id'                    => $txId,
                'transaction_code'      => 'TXN-' . $createdAt->format('Ymd') . '-' . strtoupper(Str::random(6)),
                'idempotency_key'       => 'SEED-' . strtoupper(Str::random(16)),
                'subsystem_id'          => $tx['subsystem_id'],
                'source_module'         => $tx['source_module'],
                'external_reference_id' => $tx['external_reference_id'],
                'type'                  => $tx['type'],
                'amount'                => $tx['amount'],
                'tax_amount'            => $tx['tax_amount'],
                'fee_amount'            => $tx['fee_amount'],
                'net_amount'            => $netAmount,
                'currency'              => 'PHP',
                'description'           => $tx['description'],
                'metadata'              => json_encode([]),
                'status'                => $tx['status'],
                'ai_confidence_score'   => $tx['ai_confidence_score'],
                'ai_suggested_gl_code'  => $tx['ai_suggested_gl_code'],
                'ai_suggested_gl_name'  => $tx['ai_suggested_gl_name'],
                'ai_anomaly_flag'       => $tx['ai_anomaly_flag'],
                'ai_anomaly_reason'     => $tx['ai_anomaly_reason'],
                'approved_by'           => null,
                'approved_at'           => $tx['status'] === 'approved' ? $createdAt->copy()->addHours(rand(1, 4)) : null,
                'posted_at'             => null,
                'created_at'            => $createdAt,
                'updated_at'            => $createdAt,
            ]);

            // AI log for audit trail
            DB::table('ai_logs')->insert([
                'id'             => (string) Str::uuid(),
                'transaction_id' => $txId,
                'anomaly_score'  => $tx['ai_confidence_score'] * 100,
                'ai_decision'    => $tx['ai_anomaly_flag'] ? 'FLAGGED' : 'PASSED',
                'flag_reason'    => $tx['ai_anomaly_reason'],
                'created_at'     => $createdAt,
                'updated_at'     => $createdAt,
            ]);
        }
    }
}
