<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class GeneralLedgerResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * The API Resource formats the ledger data into the simplified representation used by the capstone UI.
     * The accounting mapping follows the journal entry generated by FinancialService, and the frontend
     * only renders the values returned by the API.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        $transaction = $this->transaction;
        
        $amount = (float) $transaction->amount;
        $isExpense = $transaction->type === 'EXPENSE';
        
        return [
            'id'               => $this->id,
            'entry_number'     => $this->entry_number,
            'posted_at'        => $transaction->posted_at ? $transaction->posted_at->toIso8601String() : $this->created_at->toIso8601String(),
            'description'      => $transaction->description,
            'account_name'     => $transaction->ai_suggested_gl_name ?? 'Uncategorized Account',
            'debit'            => $isExpense ? $amount : 0.00,
            'credit'           => !$isExpense ? $amount : 0.00,
            'reference_number' => $transaction->transaction_code, // Or external_reference_id
            'source_module'    => $transaction->source_module,
            'status'           => $this->status,
        ];
    }
}
